// <auto-generated />
using System;
using CarPoolMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPoolMvc.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("CarPoolLibrary.Models.Manifest", b =>
                {
                    b.Property<int>("ManifestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TripId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("ManifestId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ManifestId", "MemberId")
                        .IsUnique();

                    b.ToTable("Manifest", (string)null);

                    b.HasData(
                        new
                        {
                            ManifestId = 1,
                            MemberId = 1,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(710),
                            CreatedBy = "System",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(710),
                            ModifiedBy = "System",
                            Notes = "I will be driving to work",
                            TripId = 1
                        },
                        new
                        {
                            ManifestId = 2,
                            MemberId = 2,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(720),
                            CreatedBy = "System",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(720),
                            ModifiedBy = "System",
                            Notes = "I will be driving to work",
                            TripId = 2
                        },
                        new
                        {
                            ManifestId = 3,
                            MemberId = 3,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(720),
                            CreatedBy = "System",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(720),
                            ModifiedBy = "System",
                            Notes = "I will be driving to work",
                            TripId = 3
                        });
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("MemberId");

                    b.ToTable("Member", (string)null);

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            City = "Richmond",
                            Country = "Canada",
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(350),
                            CreatedBy = "System",
                            Email = "sam@fox.com",
                            FirstName = "Sam",
                            LastName = "Fox",
                            Mobile = "778-111-2222",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(390),
                            ModifiedBy = "System",
                            PostalCode = "V4F 1M7",
                            Street = "457 Fox Avenue"
                        },
                        new
                        {
                            MemberId = 2,
                            City = "Delta",
                            Country = "Canada",
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(420),
                            CreatedBy = "System",
                            Email = "ann@day.com",
                            FirstName = "Ann",
                            LastName = "Day",
                            Mobile = "604-333-6666",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(420),
                            ModifiedBy = "System",
                            PostalCode = "V6G 1M6",
                            Street = "231 Reiver Road"
                        },
                        new
                        {
                            MemberId = 3,
                            City = "Delta",
                            Country = "Canada",
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(420),
                            CreatedBy = "System",
                            Email = "lucas@jian.com",
                            FirstName = "Lucas",
                            LastName = "Jian",
                            Mobile = "604-333-6666",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(420),
                            ModifiedBy = "System",
                            PostalCode = "V6G 1M6",
                            Street = "231 Reiver Road"
                        });
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TripId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TripId", "VehicleId")
                        .IsUnique();

                    b.ToTable("Trip", (string)null);

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Date = new DateOnly(2024, 2, 2),
                            Destination = "123 Marine Drive, Burnaby",
                            MeetingAddress = "1123 River Road, Coquitlam",
                            Time = new TimeOnly(12, 0, 0),
                            VehicleId = 1
                        },
                        new
                        {
                            TripId = 2,
                            Date = new DateOnly(2024, 2, 3),
                            Destination = "231 Boundary Road, Vancouver",
                            MeetingAddress = "345 King George Highway, Surrey",
                            Time = new TimeOnly(8, 0, 0),
                            VehicleId = 2
                        },
                        new
                        {
                            TripId = 3,
                            Date = new DateOnly(2024, 2, 4),
                            Destination = "12345 Lougheed Highway, Coquitlam",
                            MeetingAddress = "540 Oliver Road, Richmond",
                            Time = new TimeOnly(15, 0, 0),
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.HasIndex("MemberId");

                    b.ToTable("Vehicle", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(440),
                            CreatedBy = "System",
                            Make = "Ford",
                            MemberId = 1,
                            Model = "Escort",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(440),
                            ModifiedBy = "System",
                            NumberOfSeats = 5,
                            VehicleType = "Sedan",
                            Year = 2020
                        },
                        new
                        {
                            VehicleId = 2,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(450),
                            CreatedBy = "System",
                            Make = "Kia",
                            MemberId = 2,
                            Model = "Soul",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(450),
                            ModifiedBy = "System",
                            NumberOfSeats = 5,
                            VehicleType = "Compact",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 3,
                            Created = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(450),
                            CreatedBy = "System",
                            Make = "Honda",
                            MemberId = 3,
                            Model = "Odyssey",
                            Modified = new DateTime(2024, 2, 18, 16, 13, 52, 151, DateTimeKind.Local).AddTicks(450),
                            ModifiedBy = "System",
                            NumberOfSeats = 8,
                            VehicleType = "Minivan",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "230a820c-fb7a-4808-ab92-bbb825fe67e2",
                            RoleId = "ed665b0b-5a76-4ecc-85c0-1642a86ed0d7"
                        },
                        new
                        {
                            UserId = "2a0b778f-57dc-4d70-a804-7f0f0a713af7",
                            RoleId = "50fe6afd-daa7-4eca-bc3d-a4e42dd176cf"
                        },
                        new
                        {
                            UserId = "452363e3-6567-4a4b-913d-9421274c5275",
                            RoleId = "8d20ebd0-bdac-4efd-bf6b-b57d5d8a6d24"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "ed665b0b-5a76-4ecc-85c0-1642a86ed0d7",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Description = "Administrator Role"
                        },
                        new
                        {
                            Id = "50fe6afd-daa7-4eca-bc3d-a4e42dd176cf",
                            Name = "Owner",
                            NormalizedName = "OWNER",
                            Description = "Owner Role"
                        },
                        new
                        {
                            Id = "8d20ebd0-bdac-4efd-bf6b-b57d5d8a6d24",
                            Name = "Passenger",
                            NormalizedName = "PASSENGER",
                            Description = "Passenger Role"
                        });
                });

            modelBuilder.Entity("CarPoolLibrary.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "230a820c-fb7a-4808-ab92-bbb825fe67e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48bc7ad9-33ac-4604-8b3e-3406e5515c1a",
                            Email = "a@a.a",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "A@A.A",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdWwUZMrbiO8hQsJadE6JfFPux5o72ZYAMrHVdQwRjSQf+NzaVdDX85WMbWWMpLxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5ac32923-1fbd-49c5-bad5-3a5d988ace4d",
                            TwoFactorEnabled = false,
                            UserName = "a@a.a",
                            FirstName = "Admin",
                            LastName = "Admin"
                        },
                        new
                        {
                            Id = "2a0b778f-57dc-4d70-a804-7f0f0a713af7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3beb9a9-0d97-442d-9e4d-581dd20849c7",
                            Email = "o@o.o",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "O@O.O",
                            PasswordHash = "AQAAAAIAAYagAAAAEIgTmOwLu9v5MpknbvV28ETBkFbT+N8tSAoH8wCdEn116YNLAISBO2E0ijwbShoMVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "93d12b47-2e33-4390-aa0d-f33326f434aa",
                            TwoFactorEnabled = false,
                            UserName = "o@o.o",
                            FirstName = "Owner",
                            LastName = "Owner"
                        },
                        new
                        {
                            Id = "452363e3-6567-4a4b-913d-9421274c5275",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d861f493-75f6-4c85-a02e-b9a54c384bbf",
                            Email = "p@p.p",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "P@P.P",
                            PasswordHash = "AQAAAAIAAYagAAAAEF2HHxSR9x2pMT3LVU6PqfjvSwLwgTE6N+ObjGrX6+NN1nrHtwzjFT7GvvPJ4wvceg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a26aab93-f311-460a-94c3-92612dddbe72",
                            TwoFactorEnabled = false,
                            UserName = "p@p.p",
                            FirstName = "Passenger",
                            LastName = "Passenger"
                        });
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Manifest", b =>
                {
                    b.HasOne("CarPoolLibrary.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Trip", b =>
                {
                    b.HasOne("CarPoolLibrary.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarPoolLibrary.Models.Vehicle", b =>
                {
                    b.HasOne("CarPoolLibrary.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
